=== salsabildf/ProjetFinal_C-_GrapheOriente/fichierJSON/graphschema.json
{
    "$schema": "http://json-schema.org/draft-06/schema#",
    "$ref": "#/definitions/SchemaGraphe",
    "definitions": {
        "SchemaGraphe": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "etiquette": {
                    "type": "string"
                },
                "path": {
                    "type": "string"
                },
                "listeS": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/Liste"
                    }
                },
                "listeA": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ListeA"
                    }
                }
            },
            "required": [
                "etiquette",
                "listeA",
                "listeS",
                "path"
            ],
            "title": "SchemaGraphe"
        },
        "ListeA": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "id": {
                    "type": "integer"
                },
                "etiquette": {
                    "type": "string"
                },
                "IDdepart": {
                    "type": "integer"
                },
                "IDarrive": {
                    "type": "integer"
                },
                "AChargeUtile": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ChargeUtile"
                    }
                }
            },
            "required": [
                "AChargeUtile",
                "IDarrive",
                "IDdepart",
                "etiquette",
                "id"
            ],
            "title": "ListeA"
        },
        "ChargeUtile": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "mot": {
                    "type": "string"
                },
                "type": {
                    "type": "integer"
                },
                "Valeur_reel": {
                    "type": "number"
                },
                "Valeur_entiere": {
                    "type": "integer"
                }
            },
            "required": [
                "mot",
                "type"
            ],
            "title": "ChargeUtile"
        },
        "Liste": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "x": {
                    "type": "integer"
                },
                "y": {
                    "type": "integer"
                },
                "id": {
                    "type": "integer"
                },
                "etiquette": {
                    "type": "string"
                },
                "vecArc": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/VecArc"
                    }
                },
                "SChargeUtile": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/ChargeUtile"
                    }
                }
            },
            "required": [
                "SChargeUtile",
                "etiquette",
                "id",
                "vecArc",
                "x",
                "y"
            ],
            "title": "Liste"
        },
        "VecArc": {
            "type": "object",
            "additionalProperties": false,
            "properties": {
                "Tab": {
                    "type": "integer"
                }
            },
            "required": [
                "Tab"
            ],
            "title": "VecArc"
        }
    }
}

=== salsabildf/ProjetFinal_C-_GrapheOriente/fichierJSON/G1.json
{
    "etiquette": "graphe0",
    "path": "../fichierJSON/G1.json",
    "listeS": [
        {
            "x": 20,
            "y": 15,
            "id": 0,
            "etiquette": "sommet0",
            "vecArc": [
                {
                    "Tab": 1
                },
                {
                    "Tab": 4
                }
            ],
            "SChargeUtile": [
                {
                    "mot": "poid1",
                    "type": 1,
                    "Valeur_reel": 10.1
                },
                {
                    "mot": "poid2",
                    "type": 0,
                    "Valeur_entiere": 144
                }
            ]
        },
        {
            "x": 66,
            "y": 55,
            "id": 1,
            "etiquette": "sommet1",
            "vecArc": [
                {
                    "Tab": 2
                }
            ],
            "SChargeUtile": [
                {
                    "mot": "poid3",
                    "type": 1,
                    "Valeur_reel": 17.319
                },
                {
                    "mot": "poid4",
                    "type": 1,
                    "Valeur_reel": 4566.222
                }
            ]
        },
        {
            "x": 21,
            "y": 1,
            "id": 2,
            "etiquette": "sommet2",
            "vecArc": [
                {
                    "Tab": 3
                }
            ],
            "SChargeUtile": []
        }
    ],
    "listeA": [
        {
            "id": 1,
            "etiquette": "1",
            "IDdepart": 0,
            "IDarrive": 1,
            "AChargeUtile": []
        },
        {
            "id": 2,
            "etiquette": "2",
            "IDdepart": 1,
            "IDarrive": 2,
            "AChargeUtile": []
        },
        {
            "id": 3,
            "etiquette": "3",
            "IDdepart": 2,
            "IDarrive": 0,
            "AChargeUtile": []
        },
        {
            "id": 4,
            "etiquette": "4",
            "IDdepart": 0,
            "IDarrive": 2,
            "AChargeUtile": []
        }
    ]
}

=== salsabildf/ProjetFinal_C-_GrapheOriente/fichierJSON/G0modif.json
{
    "etiquette": "graphe0",
    "path": "../fichierJSON/G0modif.json",
    "listeS": [
        {
            "x": 0,
            "y": 0,
            "id": 0,
            "etiquette": "sommet0",
            "vecArc": [
                {
                    "Tab": 1
                },
                {
                    "Tab": 4
                }
            ],
            "SChargeUtile": [
                {
                    "mot": "poid1",
                    "type": 1,
                    "Valeur_reel": 10.100000381469727
                },
                {
                    "mot": "poid2",
                    "type": 0,
                    "Valeur_entiere": 144
                }
            ]
        },
        {
            "x": 0,
            "y": 0,
            "id": 1,
            "etiquette": "1",
            "vecArc": [
                {
                    "Tab": 2
                }
            ],
            "SChargeUtile": []
        },
        {
            "x": 0,
            "y": 0,
            "id": 2,
            "etiquette": "2",
            "vecArc": [
                {
                    "Tab": 3
                }
            ],
            "SChargeUtile": []
        }
    ],
    "listeA": [
        {
            "id": 1,
            "etiquette": "Arc1",
            "IDdepart": 0,
            "IDarrive": 1,
            "AChargeUtile": [
                {
                    "mot": "poid1",
                    "type": 1,
                    "Valeur_reel": 10.100000381469727
                },
                {
                    "mot": "poid2",
                    "type": 0,
                    "Valeur_entiere": 144
                }
            ]
        },
        {
            "id": 2,
            "etiquette": "2",
            "IDdepart": 1,
            "IDarrive": 2,
            "AChargeUtile": []
        },
        {
            "id": 3,
            "etiquette": "3",
            "IDdepart": 2,
            "IDarrive": 0,
            "AChargeUtile": []
        },
        {
            "id": 4,
            "etiquette": "4",
            "IDdepart": 0,
            "IDarrive": 2,
            "AChargeUtile": []
        }
    ]
}
